name: Check pihole/pihole:latest version

on: workflow_dispatch

jobs:
  pihole_inspect_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull and inspect pihole/pihole:latest
        id: eval_pihole_version
        run: |
              docker pull pihole/pihole:latest
              echo ::set-output name=version::$(docker image inspect --format '{{ index .Config.Labels "org.opencontainers.image.version"}}' pihole/pihole:latest)

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Eval repo version
        id: eval_our_version
        run: echo ::set-output name=version::$(cat VERSION)

      - name: Modify version in VERSION
        run: echo "${{ steps.eval_pihole_version.outputs.version }}" > VERSION
        if: ${{ steps.eval_our_version.outputs.version != steps.eval_pihole_version.outputs.version }}

      - name: Git Auto Commit
        id: git-auto-commit
        uses: stefanzweifel/git-auto-commit-action@v4.15.0
        with:
          commit_message: "Auto-Commit: Bump version to ${{ steps.eval_pihole_version.outputs.version }}"
        if: ${{ steps.eval_our_version.outputs.version != steps.eval_pihole_version.outputs.version }}

  docker_build_push:
    needs: pihole_inspect_version
    if: ${{ needs.auto-commit-action.outputs.changes_detected == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Eval version
        id: eval_version
        run: echo ::set-output name=version::$(cat VERSION)

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          push: true
          tags: danidelaria/pihole-unbound:latest,danidelaria/pihole-unbound:${{ steps.eval_version.outputs.version }}
