name: danidelaria/pihole-unbound build and push

on:
  push:
    branches: [ "main" ]

jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Eval version
        id: eval_version
        run: echo ::set-output name=version::$(cat VERSION)

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          push: true
          tags: danidelaria/pihole-unbound:latest,danidelaria/pihole-unbound:${{ steps.eval_version.outputs.version }}
